### ISSUE TITLE
How to deal with the different action space or observation dimensions of multiple agents

### ISSUE THREAD

**Issue by zkzfor** [PKU-MARL/HARL#14]
I noticed that your algorithm is a heterogeneous multi-agent algorithm, so I want to create a multi-agent testing environment where the observation space and action space are different for each agent, but a simple setup would pose challenges：
```
(harl) /mnt/workspace/HARL/examples> python test.py
choose to use gpu...
share_observation_space:  [Box(0.0, 1.0, (54,), float32), Box(0.0, 1.0, (54,), float32), Box(0.0, 1.0, (54,), float32)]
observation_space:  [Box(0.0, 1.0, (17,), float32), Box(0.0, 1.0, (18,), float32), Box(0.0, 1.0, (19,), float32)]
action_space:  [Box(0.0, 1.0, (5,), float32), Box(0.0, 1.0, (6,), float32), Box(0.0, 1.0, (7,), float32)]
start warmup
/home/pai/envs/harl/lib/python3.8/site-packages/numpy/core/shape_base.py:420: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrays = [asanyarray(arr) for arr in arrays]
/mnt/workspace/HARL/harl/runners/off_policy_base_runner.py:468: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(actions).transpose(1, 0, 2)
Traceback (most recent call last):
  File "test.py", line 90, in <module>
    main()
  File "test.py", line 85, in main
    runner.run()
  File "/mnt/workspace/HARL/harl/runners/off_policy_base_runner.py", line 220, in run
    obs, share_obs, available_actions = self.warmup()
  File "/mnt/workspace/HARL/harl/runners/off_policy_base_runner.py", line 319, in warmup
    actions = self.sample_actions(available_actions)
  File "/mnt/workspace/HARL/harl/runners/off_policy_base_runner.py", line 468, in sample_actions
    return np.array(actions).transpose(1, 0, 2)
ValueError: axes don't match array
```
Unlike the environment in my previous question, this time I have modified the following parameters：
```
        self.share_observation_space = [spaces.Box(0.0, 1.0, (54,)),
                                        spaces.Box(0.0, 1.0, (54,)),
                                        spaces.Box(0.0, 1.0, (54,))]
        self.observation_space = [spaces.Box(0.0, 1.0, (17,)),
                                  spaces.Box(0.0, 1.0, (18,)),
                                  spaces.Box(0.0, 1.0, (19,))]
        self.action_space = [spaces.Box(0.0, 1.0, (5,)),
                             spaces.Box(0.0, 1.0, (6,)),
                             spaces.Box(0.0, 1.0, (7,))]
```
The complete environment code is as follows:
```
import copy
import numpy as np

# import os

import gymnasium
from gymnasium import spaces
from gymnasium.utils import seeding

# logging.basicConfig()
# logging.getLogger().setLevel(logging.ERROR)


class LeoHapEnv:
    def __init__(self, args):
        # self.env = ...
        self.n_agents = 3
        self.max_cycles = 25
        self.cur_step = 0
        self.share_observation_space = [spaces.Box(0.0, 1.0, (54,)),
                                        spaces.Box(0.0, 1.0, (54,)),
                                        spaces.Box(0.0, 1.0, (54,))]
        self.observation_space = [spaces.Box(0.0, 1.0, (17,)),
                                  spaces.Box(0.0, 1.0, (18,)),
                                  spaces.Box(0.0, 1.0, (19,))]
        self.action_space = [spaces.Box(0.0, 1.0, (5,)),
                             spaces.Box(0.0, 1.0, (6,)),
                             spaces.Box(0.0, 1.0, (7,))]

    def step(self, actions):
        self.cur_step += 1
        obs = []
        for agent_n in range(self.n_agents):
            obs.append(self.observation_space[agent_n].sample())

        state = []
        for agent_n in range(self.n_agents):
            state.append(self.share_observation_space[agent_n].sample())

        rewards = [[np.random.uniform(low=0.0, high=1.0, size=None)]] * self.n_agents

        infos = []
        for agent_n in range(self.n_agents):
            info = {}
            infos.append(info)

        dones = []
        if self.cur_step == self.max_cycles:
            for agent_n in range(self.n_agents):
                done = True
                infos[agent_n]["bad_transition"] = True
                dones.append(done)
        else:
            for agent_n in range(self.n_agents):
                done = False
                dones.append(done)

        return obs, state, rewards, dones, infos, None

    def reset(self):

        self.cur_step = 0

        obs = []
        for agent_n in range(self.n_agents):
            obs.append(self.observation_space[agent_n].sample())

        state = []
        for agent_n in range(self.n_agents):
            state.append(self.share_observation_space[agent_n].sample())
        
        # available_actions = None

        return obs, state, None

    def seed(self, seed):
        pass

    def render(self):
        pass

    def close(self):
        pass
```
What aspects should be considered when writing a heterogeneous multi-agent environment, and which operations are mandatory?

**Comment by zkzfor** [comment]
Perhaps I should modify the HASAC algorithm by following the approach of the MADDPG algorithm, constructing multiple critic networks, LoL

**Comment by Ivan-Zhong** [comment]
Hello.

To handle different observation spaces and action spaces of multiple agents, their observations and actions have to be padded to the same shape for batch processing. For example, in mpe environment, we use `supersuit` to [pad](https://github.com/PKU-MARL/HARL/blob/fb6510357e8e9b751655176cc11ce45d605dece6/harl/envs/pettingzoo_mpe/pettingzoo_mpe_env.py#L30); in mamujoco environment, we [set the same spaces for all agents](https://github.com/PKU-MARL/HARL/blob/fb6510357e8e9b751655176cc11ce45d605dece6/harl/envs/mamujoco/multiagent_mujoco/mujoco_multi.py#L138), and [remove dummy actions in the step function](https://github.com/PKU-MARL/HARL/blob/fb6510357e8e9b751655176cc11ce45d605dece6/harl/envs/mamujoco/multiagent_mujoco/mujoco_multi.py#L160). So you may also need to do the padding manually to support different spaces.

That being said, it is possible to directly support different spaces in this code base, if the data processing logic is modified accordingly. The downside is that the data will not be handled with `ndarray` and can be less efficient and elegant. We may consider supporting this in the future if there is sufficient need.

**Comment by zkzfor** [comment]
Thanks for your answer, I decided to avoid the heterogeneous space problem, and I hope I can participate in the improvement of your code in the future：）

**Comment by xiaoliu-syd** [comment]
I am wondering why a heterogeneous multi-agent algorithm can not easily support different observation space and action space are  for each agent.
